-- Esquema de producción para David Basto Real Estate.
-- Compatible con la tabla tabular de inmuebles que usa el panel y el catálogo público.
create extension if not exists pgcrypto;

create table if not exists public.admin_users (
  user_id uuid primary key references auth.users(id) on delete cascade,
  created_at timestamptz not null default now()
);

create table if not exists public.property_types (
  id text primary key,
  label text not null unique,
  description text not null default '',
  sort_order integer not null default 0,
  created_at timestamptz not null default now()
);

insert into public.property_types (id, label, description, sort_order) values
  ('casa', 'Casa', 'Viviendas unifamiliares, familiares y campestres.', 1),
  ('apartamento', 'Apartamento', 'Apartamentos, apartaestudios, lofts, dúplex y penthouses.', 2),
  ('villa', 'Villa', 'Villas y casas de descanso de formato amplio.', 3),
  ('lote', 'Lote', 'Terrenos para desarrollo residencial o comercial.', 4),
  ('comercial', 'Comercial', 'Locales y espacios para actividad comercial.', 5)
on conflict (id) do update
set label = excluded.label, description = excluded.description, sort_order = excluded.sort_order;

create table if not exists public.properties (
  id bigint generated by default as identity primary key,
  title text not null,
  slug text not null unique,
  description text not null default '',
  price numeric(16,2) not null default 0,
  location text not null default '',
  municipality text not null default '',
  "ubicación" text not null default '',
  lat numeric(10,7) not null default 0,
  lng numeric(10,7) not null default 0,
  bedrooms integer not null default 0,
  bathrooms integer not null default 0,
  area numeric(10,2) not null default 0,
  type text not null,
  category_id text not null references public.property_types(id) on update cascade on delete restrict,
  status text not null default 'En Venta',
  images text[] not null default '{}',
  features text[] not null default '{}',
  categories text[] not null default '{}',
  payment text[] not null default '{}',
  featured boolean not null default false,
  is_published boolean not null default true,
  updated_at timestamptz not null default now(),
  created_at timestamptz not null default now()
);

alter table public.properties
  add column if not exists municipality text not null default '',
  add column if not exists "ubicación" text not null default '',
  add column if not exists categories text[] not null default '{}',
  add column if not exists payment text[] not null default '{}',
  add column if not exists featured boolean not null default false,
  add column if not exists is_published boolean not null default true,
  add column if not exists updated_at timestamptz not null default now(),
  add column if not exists category_id text;

do $$
begin
  if not exists (
    select 1 from pg_constraint
    where conname = 'properties_category_id_fkey'
      and conrelid = 'public.properties'::regclass
  ) then
    alter table public.properties add constraint properties_category_id_fkey
      foreign key (category_id) references public.property_types(id)
      on update cascade on delete restrict;
  end if;
end
$$;

update public.properties p
set municipality = coalesce(nullif(trim(split_part(p.location, ',', 1)), ''), ''),
    "ubicación" = coalesce(nullif(trim(split_part(p.location, ',', 2)), ''), ''),
    category_id = pt.id,
    categories = case
      when p.type = 'Comercial' then array['Buy', 'Commercial']::text[]
      when p.slug = 'condominio-bambu-carmen-de-apicala' then array['Buy', 'Projects']::text[]
      when p.status ilike '%arriendo%' then array['Rent']::text[]
      else array['Buy']::text[]
    end,
    payment = case
      when p.slug = 'condominio-bambu-carmen-de-apicala' then array[
        '30% de cuota inicial',
        'Pagos mensuales según certificación de avance de obra',
        'Esquema transparente y seguro'
      ]::text[]
      else coalesce(p.payment, '{}'::text[])
    end,
    featured = p.slug = 'condominio-bambu-carmen-de-apicala',
    updated_at = coalesce(p.updated_at, p.created_at, now())
from public.property_types pt
where lower(p.type) = lower(pt.label);

alter table public.properties alter column category_id set not null;
create index if not exists properties_category_id_idx on public.properties(category_id);
create index if not exists properties_published_updated_idx on public.properties(is_published, updated_at desc);
create unique index if not exists properties_single_featured_idx on public.properties(featured) where featured;

create or replace function public.sync_property_category_id()
returns trigger language plpgsql set search_path = public as $$
declare resolved_category text;
begin
  select id into resolved_category
  from public.property_types
  where lower(label) = lower(new.type);
  if resolved_category is null then
    raise exception 'Tipo de inmueble no registrado: %', coalesce(new.type, '(vacío)');
  end if;
  new.category_id := resolved_category;
  new.updated_at := now();
  return new;
end;
$$;

drop trigger if exists properties_sync_category_id on public.properties;
create trigger properties_sync_category_id
before insert or update of type on public.properties
for each row execute function public.sync_property_category_id();

create or replace function public.set_featured_property(target_id bigint)
returns void
language plpgsql
security invoker
set search_path = public
as $$
declare admin_allowed boolean;
begin
  select exists (
    select 1 from public.admin_users
    where user_id = (select auth.uid())
  ) into admin_allowed;

  if not admin_allowed then
    raise exception 'Solo un administrador puede destacar una propiedad.';
  end if;

  update public.properties set featured = false, updated_at = now()
  where featured = true and id <> target_id;

  update public.properties set featured = true, updated_at = now()
  where id = target_id;

  if not found then
    raise exception 'No se encontró la propiedad solicitada.';
  end if;
end;
$$;

revoke execute on function public.set_featured_property(bigint) from public, anon;
grant execute on function public.set_featured_property(bigint) to authenticated;

create table if not exists public.site_settings (
  id text primary key default 'brand',
  data jsonb not null,
  updated_at timestamptz not null default now(),
  constraint site_settings_single_brand check (id = 'brand')
);

alter table public.admin_users enable row level security;
alter table public.properties enable row level security;
alter table public.property_types enable row level security;
alter table public.site_settings enable row level security;

grant select on public.admin_users to authenticated;
grant select, insert, update, delete on public.properties, public.property_types, public.site_settings to authenticated;
grant select on public.properties, public.property_types, public.site_settings to anon;

drop policy if exists "Admins can see their own allow-list entry" on public.admin_users;
create policy "Admins can see their own allow-list entry" on public.admin_users
  for select to authenticated using (user_id = (select auth.uid()));

drop policy if exists "Published listings are public; admins can see all" on public.properties;
drop policy if exists "Published property catalog is public" on public.properties;
create policy "Published listings are public; admins can see all" on public.properties
  for select to anon, authenticated
  using (is_published or exists (select 1 from public.admin_users where user_id = (select auth.uid())));
drop policy if exists "Admins can add listings" on public.properties;
drop policy if exists "Admins can add properties" on public.properties;
create policy "Admins can add listings" on public.properties
  for insert to authenticated with check (exists (select 1 from public.admin_users where user_id = (select auth.uid())));
drop policy if exists "Admins can edit listings" on public.properties;
drop policy if exists "Admins can edit properties" on public.properties;
create policy "Admins can edit listings" on public.properties
  for update to authenticated
  using (exists (select 1 from public.admin_users where user_id = (select auth.uid())))
  with check (exists (select 1 from public.admin_users where user_id = (select auth.uid())));
drop policy if exists "Admins can delete listings" on public.properties;
drop policy if exists "Admins can delete properties" on public.properties;
create policy "Admins can delete listings" on public.properties
  for delete to authenticated using (exists (select 1 from public.admin_users where user_id = (select auth.uid())));

drop policy if exists "Property types are public" on public.property_types;
create policy "Property types are public" on public.property_types
  for select to anon, authenticated using (true);
drop policy if exists "Admins can add property types" on public.property_types;
create policy "Admins can add property types" on public.property_types
  for insert to authenticated with check (exists (select 1 from public.admin_users where user_id = (select auth.uid())));
drop policy if exists "Admins can edit property types" on public.property_types;
create policy "Admins can edit property types" on public.property_types
  for update to authenticated
  using (exists (select 1 from public.admin_users where user_id = (select auth.uid())))
  with check (exists (select 1 from public.admin_users where user_id = (select auth.uid())));
drop policy if exists "Admins can delete property types" on public.property_types;
create policy "Admins can delete property types" on public.property_types
  for delete to authenticated using (exists (select 1 from public.admin_users where user_id = (select auth.uid())));

drop policy if exists "Brand settings are public" on public.site_settings;
create policy "Brand settings are public" on public.site_settings
  for select to anon, authenticated using (true);
drop policy if exists "Admins can add brand settings" on public.site_settings;
create policy "Admins can add brand settings" on public.site_settings
  for insert to authenticated with check (exists (select 1 from public.admin_users where user_id = (select auth.uid())));
drop policy if exists "Admins can edit brand settings" on public.site_settings;
create policy "Admins can edit brand settings" on public.site_settings
  for update to authenticated
  using (exists (select 1 from public.admin_users where user_id = (select auth.uid())))
  with check (exists (select 1 from public.admin_users where user_id = (select auth.uid())));

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('property-images', 'property-images', true, 10485760, array['image/jpeg','image/png','image/webp','image/avif'])
on conflict (id) do update set public = excluded.public, file_size_limit = excluded.file_size_limit, allowed_mime_types = excluded.allowed_mime_types;

drop policy if exists "Property photos can be viewed publicly" on storage.objects;
create policy "Property photos can be viewed publicly" on storage.objects
  for select to anon, authenticated using (bucket_id = 'property-images');
drop policy if exists "Admins can upload property photos" on storage.objects;
create policy "Admins can upload property photos" on storage.objects
  for insert to authenticated
  with check (bucket_id = 'property-images' and exists (select 1 from public.admin_users where user_id = (select auth.uid())));
drop policy if exists "Admins can replace property photos" on storage.objects;
create policy "Admins can replace property photos" on storage.objects
  for update to authenticated
  using (bucket_id = 'property-images' and exists (select 1 from public.admin_users where user_id = (select auth.uid())))
  with check (bucket_id = 'property-images' and exists (select 1 from public.admin_users where user_id = (select auth.uid())));
drop policy if exists "Admins can remove property photos" on storage.objects;
create policy "Admins can remove property photos" on storage.objects
  for delete to authenticated
  using (bucket_id = 'property-images' and exists (select 1 from public.admin_users where user_id = (select auth.uid())));

