"use client";
import Link from "next/link";
import DriveImage from "@/components/DriveImage";
import { ArrowDown, ArrowRight, ArrowUpRight, ShieldCheck, Sparkles, MapPin, MoveUpRight } from "lucide-react";
import { properties } from "@/data/properties";
import { formatCOP } from "@/data/properties";
import PropertyListings from "@/components/PropertyListings";
import MapView from "@/components/MapView";
import HomeSearch from "@/components/HomeSearch";
import MapCount from "@/components/MapCount";
import { usePropertyApp } from "@/components/AppProvider";
export default function Home() { const { allProperties, settings, contentLoaded }=usePropertyApp(); const featured = allProperties.find(p => p.featured) ?? allProperties[0] ?? properties[0]; return <main className="home-modern">
  <section className="hero"><DriveImage className="hero-image media-fill" src={settings.heroImage || featured.image} alt={featured.name} highPriority/><div className="hero-shade"/><div className="hero-content"><div className="hero-kicker"><span/> INVERSIÓN INMOBILIARIA · COLOMBIA</div><h1>{settings.heroTitle}<br/><em>{settings.heroAccent}</em></h1><p className="hero-description">{settings.heroDescription}</p><div className="hero-actions"><a href="#propiedades" className="button button-gold">Explorar propiedades <ArrowUpRight size={17}/></a><a href="#mapa" className="hero-text-link">Descubrir el mapa <ArrowDown size={15}/></a></div></div><div className="hero-bottom"><span>01 — 03</span><span>DESLIZA PARA EXPLORAR</span></div>{allProperties.length>0&&<div className="hero-feature"><span className="feature-icon">✳</span><span>PROPIEDAD DESTACADA</span><b>{featured.name}</b><small>Desde {formatCOP(featured.price)}</small></div>}{!contentLoaded&&<span className="site-loading" aria-label="Cargando catálogo"/>}</section>
  <HomeSearch/><section className="intro section-wrap"><div className="eyebrow"><span/> UNA NUEVA FORMA DE ENCONTRAR HOGAR</div><div className="intro-grid"><h2>Elegir dónde vivir<br/>es elegir <em>cómo vivir.</em></h2><div><p>Acompañamiento cercano, información transparente y espacios que se sienten como tuyos desde el primer momento.</p><a className="under-link" href="#sobre-mi">Conoce mi forma de trabajar <ArrowRight size={16}/></a></div></div><div className="trust-row"><div><ShieldCheck/><span><b>Confianza en cada paso</b><small>Transparencia de principio a fin</small></span></div><div><Sparkles/><span><b>Espacios con propósito</b><small>Selección pensada para tu vida</small></span></div><div><MapPin/><span><b>Asesoría personal</b><small>Conocimiento local, trato humano</small></span></div></div></section>
  <section id="propiedades" className="properties-section"><div className="section-wrap"><div className="section-heading"><div><div className="eyebrow"><span/> SELECCIÓN PARA TI</div><h2>Encuentra tu <em>espacio.</em></h2></div><a href="#mapa" className="under-link">Ver en el mapa <MoveUpRight size={16}/></a></div><PropertyListings/></div></section>
  <section id="mapa" className="map-section"><div className="section-wrap"><div className="section-heading map-heading"><div><div className="eyebrow"><span/> ENCUENTRA TU LUGAR</div><h2>Propiedades en <em>el mapa.</em></h2></div><p>Explora oportunidades en destinos<br/>que invitan a vivir distinto.</p></div><div className="map-frame"><MapView/><MapCount/></div></div></section>
  <section id="sobre-mi" className="advisor-section"><div className="advisor-photo"><DriveImage className="media-fill" src={settings.advisorImage} alt={`Asesor inmobiliario ${settings.contactName}`}/></div><div className="advisor-copy"><div className="eyebrow"><span/> ASESORÍA PERSONAL</div><h2>Hola, soy {settings.contactName.split(" ")[0]}.<br/><em>Hagámoslo posible.</em></h2><p>Como ingeniero civil y asesor inmobiliario, conozco cada detalle que convierte una propiedad en una buena decisión. Estoy aquí para acompañarte con claridad, experiencia y cercanía.</p><a href={`https://wa.me/${settings.whatsappPhone}?text=${encodeURIComponent(`Hola ${settings.contactName}, quiero conversar sobre mi próxima propiedad.`)}`} className="button button-dark" target="_blank" rel="noreferrer">Conversemos <ArrowUpRight size={17}/></a><div className="advisor-signature">{settings.contactName} <small>{settings.contactRole.toUpperCase()}</small></div></div></section>
  <section className="closing-cta"><div className="eyebrow"><span/> TU PRÓXIMO CAPÍTULO TE ESPERA</div><h2>¿Lo imaginamos <em>juntos?</em></h2>{allProperties[0]&&<Link className="button button-gold" href={`/propiedades/${featured.slug}`}>Descubre {featured.name} <ArrowRight size={17}/></Link>}</section>
 </main>; }
