"use client";
import DriveImage from "@/components/DriveImage";
import Link from "next/link";
import { ArrowLeft, ArrowUpRight, Bath, BedDouble, Check, Heart, MapPin, Maximize2, ShieldCheck } from "lucide-react";
import { formatCOP } from "@/data/properties";
import { usePropertyApp } from "@/components/AppProvider";
export default function PropertyDetailClient({ slug }: { slug: string }) {
  const { allProperties, contentLoaded, settings, favorites, toggleFavorite } = usePropertyApp();
  const legacyAliases: Record<string, string> = { "condominio-bambu": "condominio-bambu-carmen-de-apicala" };
  const p = allProperties.find(item => item.slug === slug || item.slug === legacyAliases[slug]);
  if (!contentLoaded) return <main className="detail-page"><div className="detail-wrap"><p className="admin-status">Cargando ficha del inmueble…</p></div></main>;
  if (!p) return <main className="detail-page"><div className="detail-wrap"><Link href="/buscar" className="back-link"><ArrowLeft size={16}/> Volver a propiedades</Link><div className="empty-state"><b>Esta propiedad ya no está publicada</b><Link href="/buscar">Ver otras propiedades</Link></div></div></main>;
  const photos = p.gallery?.length ? p.gallery : [p.image];
  const message = encodeURIComponent(`Hola ${settings.contactName}, quiero más información sobre ${p.name}.`);
  const phone=settings.whatsappPhone.replace(/\D/g,"");
  return <main className="detail-page"><div className="detail-wrap"><Link href="/#propiedades" className="back-link"><ArrowLeft size={16}/> Volver a propiedades</Link><div className="detail-title"><div><div className="eyebrow"><span/> {p.type.toUpperCase()} · {p.status.toUpperCase()}</div><h1>{p.name}</h1><p><MapPin size={16}/>{p.location}</p></div><div className="detail-title-actions"><div className="detail-price"><small>PRECIO DESDE</small><b>{formatCOP(p.price)}</b></div><button className={`favorite-button detail-favorite ${favorites.includes(p.id)?"saved":""}`} onClick={()=>toggleFavorite(p.id)} aria-label="Guardar propiedad"><Heart size={17} fill={favorites.includes(p.id)?"currentColor":"none"}/></button></div></div><div className="gallery"><div className="gallery-main"><DriveImage className="media-fill" src={photos[0]} alt={`${p.name}, vista principal`} highPriority/></div>{photos.slice(1,3).map((img,i)=><div className="gallery-side" key={`${img}-${i}`}><DriveImage className="media-fill" src={img} alt={`${p.name}, espacio ${i+2}`}/></div>)}<span className="gallery-count">01 / {String(photos.length).padStart(2,"0")} · GALERÍA</span></div><div className="detail-layout"><div className="detail-main"><div className="spec-row"><div><Maximize2/><b>{p.area} m²</b><small>Área construida</small></div><div><BedDouble/><b>{p.bedrooms}</b><small>Habitaciones</small></div><div><Bath/><b>{p.bathrooms}</b><small>Baños</small></div></div><section className="detail-block"><div className="eyebrow"><span/> EL ESPACIO</div><h2>Un lugar para <em>sentirte en casa.</em></h2><p>{p.description}</p></section><section className="detail-block"><div className="eyebrow"><span/> LO QUE HACE ESPECIAL</div><div className="amenity-grid">{p.amenities.map(item=><div key={item}><Check size={17}/>{item}</div>)}</div></section><section className="detail-block payment-block"><div className="eyebrow"><span/> COMPRA CON TRANQUILIDAD</div><h2>Un plan claro, <em>paso a paso.</em></h2>{p.payment.map((item,i)=><div className="payment-step" key={item}><span>0{i+1}</span><b>{item}</b></div>)}<p className="payment-note"><ShieldCheck size={16}/> Condiciones sujetas a disponibilidad. Te explico cada detalle personalmente.</p></section></div><aside className="contact-card"><div className="contact-mark">{settings.brandMark}</div><div className="eyebrow"><span/> ASESOR PERSONAL</div><h3>{settings.contactName}</h3><p>{settings.contactRole}</p><div className="contact-divider"/><span className="contact-question">¿Quieres conocer más sobre esta propiedad?</span><a className="button button-dark contact-button" href={`https://wa.me/${phone}?text=${message}`} target="_blank" rel="noreferrer">Consultar por WhatsApp <ArrowUpRight size={17}/></a><a className="contact-tel" href={`tel:${phone}`}>{settings.phone}</a><small>Respuesta personal, sin compromiso.</small></aside></div></div></main>;
}
