"use client";
import Link from "next/link";
import { useState, type FormEvent } from "react";
import { ArrowLeft, KeyRound, ShieldCheck } from "lucide-react";
import { useRouter } from "next/navigation";
import { getSupabaseClient, supabaseConfigured } from "@/lib/supabase/client";
export default function AdminLoginPage(){const [email,setEmail]=useState("");const [password,setPassword]=useState("");const [message,setMessage]=useState("");const [busy,setBusy]=useState(false);const router=useRouter();async function handleLogin(event:FormEvent<HTMLFormElement>){event.preventDefault();const supabase=getSupabaseClient();if(!supabase){setMessage("Primero conecta el proyecto de Supabase en la configuración de la app.");return;}setBusy(true);setMessage("");const {data,error}=await supabase.auth.signInWithPassword({email,password});if(error||!data.user){setMessage("No pudimos iniciar sesión. Revisa tu correo y contraseña.");setBusy(false);return;}const {data:access,error:accessError}=await supabase.from("admin_users").select("user_id").eq("user_id",data.user.id).maybeSingle();if(accessError||!access){await supabase.auth.signOut();setMessage("Esta cuenta todavía no tiene permiso de administrador.");setBusy(false);return;}const requestedPath=new URLSearchParams(window.location.search).get("next");const nextPath=requestedPath?.startsWith("/")&&!requestedPath.startsWith("//")?requestedPath:"/admin";router.replace(nextPath);}
return <main className="admin-login-page"><Link href="/" className="back-link"><ArrowLeft size={16}/> Volver al sitio</Link><section className="admin-login-card"><div className="admin-lock"><ShieldCheck size={23}/></div><div className="eyebrow"><span/> ÁREA PRIVADA</div><h1>Administrar el sitio</h1><p>Accede con la cuenta autorizada para gestionar propiedades y diseño.</p>{!supabaseConfigured&&<div className="admin-notice">Falta conectar Supabase. Copia las variables de <code>.env.example</code> en <code>.env.local</code> para activar el acceso.</div>}<form onSubmit={handleLogin}><label>Correo electrónico<input type="email" autoComplete="username" required value={email} onChange={e=>setEmail(e.target.value)} placeholder="tu@correo.com"/></label><label>Contraseña<input type="password" autoComplete="current-password" required value={password} onChange={e=>setPassword(e.target.value)} placeholder="••••••••"/></label><button className="button button-dark" disabled={busy||!supabaseConfigured}><KeyRound size={16}/>{busy?"Ingresando…":"Ingresar al administrador"}</button></form>{message&&<p className="admin-error" role="alert">{message}</p>}<small>El acceso se controla con una lista privada de administradores.</small></section></main>;
}
