-- V2 additive migration for the existing production properties table.
-- Run once in Supabase SQL Editor after reviewing the deployment notes in README.md.
begin;

create schema if not exists extensions;
create extension if not exists postgis with schema extensions;
create schema if not exists net;
create extension if not exists pg_net with schema net;

-- Keep the existing columns (including lat/lng and images) and data intact.
alter table public.properties
  add column if not exists coordinates extensions.geography(Point, 4326);

create or replace function public.sync_property_coordinates()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  if new.lat between -90 and 90 and new.lng between -180 and 180
     and (new.lat <> 0 or new.lng <> 0) then
    new.coordinates := extensions.st_setsrid(extensions.st_makepoint(new.lng, new.lat), 4326)::extensions.geography;
  else
    new.coordinates := null;
  end if;
  return new;
end;
$$;

drop trigger if exists properties_sync_coordinates on public.properties;
create trigger properties_sync_coordinates
before insert or update of lat, lng on public.properties
for each row execute function public.sync_property_coordinates();

update public.properties
set coordinates = extensions.st_setsrid(extensions.st_makepoint(lng, lat), 4326)::extensions.geography
where lat between -90 and 90 and lng between -180 and 180
  and (lat <> 0 or lng <> 0) and coordinates is null;

create index if not exists properties_coordinates_gist_idx
  on public.properties using gist (coordinates);

create or replace function public.get_properties_in_bounds(bounds_wkt text)
returns table (
  id bigint,
  title text,
  slug text,
  price numeric,
  type text,
  area numeric,
  bedrooms integer,
  bathrooms integer,
  location text,
  lat numeric,
  lng numeric,
  status text,
  image text
)
language plpgsql
stable
security invoker
set search_path = ''
as $$
begin
  if bounds_wkt is null or length(bounds_wkt) > 2000 or bounds_wkt not ilike 'POLYGON((%' then
    raise exception 'Bounds must be a valid WKT polygon.' using errcode = '22023';
  end if;

  return query
  select p.id, p.title, p.slug, p.price, p.type, p.area, p.bedrooms, p.bathrooms,
         p.location, p.lat, p.lng, p.status, p.images[1]
  from public.properties p
  where p.coordinates is not null
    and extensions.st_intersects(p.coordinates, extensions.st_geogfromtext(bounds_wkt));
end;
$$;

revoke all on function public.get_properties_in_bounds(text) from public;
grant execute on function public.get_properties_in_bounds(text) to anon, authenticated;

-- In Supabase Dashboard > Storage > Buckets > property-images, allow:
-- image/jpeg, image/png, image/webp, image/avif, image/gif,
-- video/mp4, video/webm, video/quicktime; set the bucket max to 25 MiB.
-- Do this in the Storage UI; the Storage schema is managed by Supabase.

create table if not exists public.leads (
  id bigint generated by default as identity primary key,
  name text not null check (length(btrim(name)) between 2 and 100),
  phone_number text not null check (length(regexp_replace(phone_number, '[^0-9]', '', 'g')) between 7 and 15),
  interested_property_id bigint references public.properties(id) on delete set null,
  created_at timestamptz not null default now()
);

create index if not exists leads_created_at_idx on public.leads(created_at desc);
create index if not exists leads_property_idx on public.leads(interested_property_id);

alter table public.leads enable row level security;
revoke all on public.leads from anon, authenticated;
grant insert (name, phone_number, interested_property_id) on public.leads to anon, authenticated;
grant select on public.leads to authenticated;

drop policy if exists "Public can submit a lead" on public.leads;
create policy "Public can submit a lead" on public.leads
  for insert to anon, authenticated
  with check (
    length(btrim(name)) between 2 and 100
    and length(regexp_replace(phone_number, '[^0-9]', '', 'g')) between 7 and 15
  );

drop policy if exists "Admins can read leads" on public.leads;
create policy "Admins can read leads" on public.leads
  for select to authenticated
  using (exists (select 1 from public.admin_users where user_id = (select auth.uid())));

-- Store the n8n webhook URL in Supabase Vault under the name n8n_webhook_url.
-- Example (replace the value with your production webhook URL before running manually):
-- select vault.create_secret('https://YOUR-N8N-HOST/webhook/YOUR-PATH', 'n8n_webhook_url', 'Lead webhook');
create or replace function public.notify_n8n_new_lead()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  endpoint text;
begin
  select decrypted_secret into endpoint
  from vault.decrypted_secrets
  where name = 'n8n_webhook_url'
  limit 1;

  if endpoint is null or endpoint = '' then
    raise warning 'n8n_webhook_url is not configured in Supabase Vault; lead stored without webhook delivery.';
    return new;
  end if;

  perform net.http_post(
    url := endpoint,
    headers := jsonb_build_object('Content-Type', 'application/json'),
    body := jsonb_build_object(
      'type', 'INSERT',
      'table', 'leads',
      'schema', 'public',
      'record', jsonb_build_object(
        'id', new.id,
        'name', new.name,
        'phone_number', new.phone_number,
        'interested_property_id', new.interested_property_id,
        'created_at', new.created_at
      )
    )
  );
  return new;
exception when others then
  -- pg_net is asynchronous; queue errors must not roll back the lead itself.
  raise warning 'Could not queue the n8n lead webhook: %', sqlerrm;
  return new;
end;
$$;

revoke all on function public.notify_n8n_new_lead() from public, anon, authenticated;
drop trigger if exists leads_notify_n8n_after_insert on public.leads;
create trigger leads_notify_n8n_after_insert
after insert on public.leads
for each row execute function public.notify_n8n_new_lead();

commit;
